### ISSUE TITLE
Allow use of `@JsonDeserialize(contentAs=XXX)` with `Optional`

### ISSUE THREAD

**Issue by sebrau** [FasterXML/jackson-datatype-jdk8#13]
From JsonDeserialize JavaDoc : 
```
    /**
     * Concrete type to deserialize content (elements
     * of a Collection/array, values of Maps) values as,
     * instead of type otherwise declared.
     * Must be a subtype of declared type; otherwise an exception may be
     * thrown by deserializer.
     */
    public Class<?> contentAs() default Void.class;
```

It should be possible to use : 
```
    @JsonDeserialize(contentAs=Foo.class)
    public void foo(Optional<IFoo> foo)
```

**Comment by cowtowncoder** [comment]
Interesting. Yes, I think that would make sense for referential types like `Optional` and `AtomicReference`. Currently this is not supported, and `contentAs` only has effect on `Collection`s and `Map`s, but may be doable (depending on how `JavaType` handling works).

**Comment by markmsmith** [comment]
+1 I encountered a need for this today while trying to force the contents of an Optional (which could be a String or a Long for an ID) to always be serialized as a String.  I'd like to be able to do:
```java
@JsonSerialize(contentAs = ToStringSerializer.class)  // always serialize non-null as a String
public Optional<Object> getEntityId() {
  return entityId;
}
```
As a workaround, I'll have to make a separate method the exists purely for serialization:
```java
@JsonProperty(value = "entityId")
public Optional<String> getEntityIdStr(){
  return getEntityId().map(Object::toString);
}
```
Not the end of the world, but it would be nicer to do it the normal Jackson way.
