### ISSUE TITLE
Missing @type when serializing Optional<Interface>

### ISSUE THREAD

**Issue by jloisel** [FasterXML/jackson-datatype-jdk8#14]
Hi,

When upgrading to jackson 2.6.0 (previously with 2.5.4), one of our object serializing fails:
> com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@type' that is to contain type id  (for class ...)

Our class has a java.util.Optional<Interface> field, where Interface is configured as following:
> @JsonTypeInfo(use = Id.NAME, include = As.PROPERTY)
> @JsonSubTypes({
>    @Type(name = "First", value = First.class),
>    @Type(name = "Second", value = Second.class)
> })
> public interface Interface {
> }

It appears that the serialized object instance lacks @type information. It works perfectly fine with Jackson 2.5.4 and below. It seems like a regression either in Jackson, or in the JDK8 module.

**Comment by cowtowncoder** [comment]
Note: also reported as duplicate as https://github.com/FasterXML/jackson-databind/issues/930, gist https://gist.github.com/jloisel/3e21cc14fb5779c2b1d3.

**Comment by jloisel** [comment]
:+1: Well done! Can't wait to get hands on 2.6.2 release.
