### ISSUE TITLE
Manifest file missing Import-Package in version 2.6.3

### ISSUE THREAD

**Issue by Quintok** [FasterXML/jackson-datatype-jdk8#21]
Hi,

the Manifest file is missing the import package  com.fasterxml.jackson.databind.introspect which is used in [OptionalSerializer.java](https://github.com/FasterXML/jackson-datatype-jdk8/blob/master/src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalSerializer.java#L12)

I'm quite happy to update it if you could point me to roughly the right spot to start.

Thanks!

**Comment by cowtowncoder** [comment]
Imports are defined in `pom.xml`, I added it. For 2.7 system actually drops explicit declarations and let's maven plug-in to automatically determine necessary imports; this should be more reliable.
But for 2.6 explicit ones are still used.

Thank you for reporting this!
