### ISSUE TITLE
Optional.empty() fields should NOT be serialized when the class has @JsonInclude(JsonInclude.Include.NON_NULL)

### ISSUE THREAD

**Issue by martins1930** [FasterXML/jackson-datatype-jdk8#24]
Hi! 

When a field has the value ```Optional.empty()```  and the class is annotated with ```@JsonInclude(JsonInclude.Include.NON_NULL)```,  then field should not be serialized.

For example if I have this main method:
```java
package jackson;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import java.util.Optional;


public class JacksonTest {


  public static void main(String[] args) throws JsonProcessingException {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new Jdk8Module());

    Contact nullEmail = new Contact("Example Co.", Optional.<String>empty());
    String nullEmailJson = mapper.writeValueAsString(nullEmail);
    System.out.println(nullEmailJson);
  }

  @JsonInclude(JsonInclude.Include.NON_NULL)
  private static class Contact {
    private final String name;
    private final Optional<String> email;

    public Contact(String name, Optional<String> email) {
      this.name = name;
      this.email = email;
    }

    public String getName() {
      return name;
    }

    public Optional<String> getEmail() {
      return email;
    }
  }

}

```

The expected behavior is that this main method prints this:
``` {"name":"Example Co."} ```

But actually the main method prints:
``` {"name":"Example Co.","email":null}  ```

Thanks,
Martin.

**Comment by martins1930** [comment]
I just realized that if I use the annotation ```@JsonInclude(JsonInclude.Include.NON_EMPTY)``` then the Optional.empty() is skipped, so that works for me, 
I think that this issue could be closed.

**Comment by cowtowncoder** [comment]
Correct; either `NON_EMPTY` or `NON_ABSENT` (added in 2.6). `NON_NULL` is reserved literally for simple Java `null` checks.

**Comment by dminkovsky** [comment]
I have a field that is `Optional<List<String>>`. When the field is set to an empty list of strings—the `Optional` is NOT empty but the `List` is empty`, the field is serialized to `[]`. Is there any way I can get it to exclude the present empty list?

**Comment by cowtowncoder** [comment]
@dminkovsky yes, `@JsonInclude` now allows both `value` (probably want to either "empty" or "absent" for that), and `content`, which applies to thing contained: here the `Collection`. So you'd define both, something like:

```java
    @JsonInclude(value=Include.NON_ABSENT, content=Include.NON_EMPTY)
```

**Comment by dminkovsky** [comment]
@cowtowncoder thank you very much!!
