### ISSUE TITLE
OptionalDoubleSerializer does not override acceptJsonFormatVisitor

### ISSUE THREAD

**Issue by osi** [FasterXML/jackson-datatype-jdk8#25]
I'm trying to generate an avro schema for a class that has an OptionalDouble. This fails since the OptionalDoubleSerializer does not override acceptJsonFormatVisitor to indicate that the contained type is a double.

(The other optional primitive wrappers also suffer from this)

**Comment by cowtowncoder** [comment]
Ok, sounds reasonable. Does regular `Optional` work however?

**Comment by osi** [comment]
The following addition to OptionalDoubleSerializer fixes the issue:

```java
    @Override
    public void acceptJsonFormatVisitor(JsonFormatVisitorWrapper visitor, JavaType typeHint)
            throws JsonMappingException
    {
        visitor.expectNumberFormat(typeHint).numberType(JsonParser.NumberType.DOUBLE);
    }
```

yes, a regular optional does work.

**Comment by cowtowncoder** [comment]
@osi Thanks. I assume similar fixes would make sense for other special optional types; I can copy handling from respective plain serializers. And see if there are unit tests to repurpose from `jackson-databind` (I think there's bit of testing for producing proper callback for schema generation).

**Comment by osi** [comment]
Yes, basically the same for Long/Int classes too.
