### ISSUE TITLE
@JsonSerialize(contentUsing = CustomSerializer.class) and @JsonDeserialize(contentUsing = CustomDeserializer.class) does not work for Optionals

### ISSUE THREAD

**Issue by selenareneephillips** [FasterXML/jackson-datatype-jdk8#31]
I have some optional fields which contain values that have custom serializers and deserializers. The @JsonSerialize and @JsonDeserialize annotations with the 'contentUsing' directive don't work. The custom serializers and deserializers are not used. I have put together a sample package that demonstrates the defect.

[defectdemo.tar.gz](https://github.com/FasterXML/jackson-datatype-jdk8/files/184324/defectdemo.tar.gz)

**Comment by cowtowncoder** [comment]
Quick verification: does this fail as expected with 2.7.3?

**Comment by cowtowncoder** [comment]
Ok. So, this is now fixed for 2.7, so will be in 2.7.4.

I also tried backporting fixes into 2.6, and was successful with serialization (works as expected), but unfortunately deserialization not so much -- type handling was rewritten between 2.6 and 2.7, and parts of those fixes are needed to get deserialization fully working.

**Comment by selenareneephillips** [comment]
Wow. That was fast. I brainfarted on using the latest version to do the test. Sorry about that. When is 2.7.4 going to be released?

**Comment by cowtowncoder** [comment]
@selenareneephillips It may take a few weeks, as 2.7.3 just went out a week ago.
Glad to hear you are not necessary tied to older version like 2.5.

**Comment by selenareneephillips** [comment]
Okay. I look forward to 2.7.4. Thanks for making such a fast fix.
