### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-datatype-jdk8#33]
hi
The following source files are without license headers. Please, add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8BeanSerializerModifier.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8Deserializers.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8Module.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8OptionalBeanPropertyWriter.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8Serializers.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8TypeModifier.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8UnwrappingOptionalBeanPropertyWriter.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalDoubleDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalDoubleSerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalIntDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalIntSerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalLongDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalLongSerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jdk8/OptionalSerializer.java

./src/test/java/com/fasterxml/jackson/failing/OptionalBasicTest.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/PolymoprhicOptionalTest.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/OptionalUnwrappedTest.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/TestOptionalWithPolymorphic.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/TestOptionalBasic.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/ModuleTestBase.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/CreatorTest.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/OptionalTest.java
./src/test/java/com/fasterxml/jackson/datatype/jdk8/TestConfigureAbsentsAsNulls.java

**Comment by cowtowncoder** [comment]
We do not add license crap in source files: LICENSE is included as a separate file.

If you need extra fluff in source files, feel free to post-process them and re-package for inclusion purposes in reproduction that for some weird reason require such padding.
