### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by mrog** [FasterXML/jackson-datatype-jdk8#35]
Is there an open source license for this project?  If so, will you please add it to the repo?

Thank you.

**Comment by stevenschlansker** [comment]
https://github.com/FasterXML/jackson-core/wiki

> Project is licensed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0.txt) like all official Jackson components.

**Comment by cowtowncoder** [comment]
@mrog I try to do DRY, which is why LICENSE is in just one place (there is a copy under `src/main/resources` that gets built into jars); this is why there isn't separate license file at project root.
