### ISSUE TITLE
2.8.1 failed, but 2.6.1 works fine 

### ISSUE THREAD

**Issue by xumingbo** [FasterXML/jackson-datatype-jdk8#39]
looks like annotation @JsonIgnore not working with version 2.7.x and 2.8.x

The following code works fine with version 2.6.1, but with v2.8.1 it failed:
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.util.Optional: no String-argument constructor/factory method to deserialize from String value ('goalTypeId')
 at [Source: {"propertyName":"goalTypeId","objectName":"order","id":21,"message":"Not a valid value for an enumerated field","key":"property.enum"}; line: 1, column: 17] 

--- here is the code ---

```java
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Optional;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@JsonRootName("validationmessages")
@NoArgsConstructor
@AllArgsConstructor
public class ValidationMessage {

    private String message;
    private String key;
    private Optional<String> objectName;
    private Optional<String> propertyName;
    private Optional<Long> id;

    public void setId(Optional<Long> id) {
        this.id = id;
    }

    @JsonIgnore
    public Optional<Long> getId() {
        return id;
    }

    @JsonProperty("id")
    public Long getMessageId() {
        return id.orElse(0L);
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @JsonIgnore
    public Optional<String> getObjectName() {
        return objectName;
    }

    @JsonProperty("objectName")
    public String getObject() {
        return objectName != null ? objectName.get().substring(0, 1).toLowerCase() + objectName.get().substring(1) : null;
    }

    public void setObjectName(Optional<String> objectName) {
        this.objectName = objectName;
    }

    public void setObject(String objectName) {
        this.objectName = Optional.ofNullable(objectName);
    }

    @JsonIgnore
    public Optional<String> getPropertyName() {
        return propertyName;
    }

    @JsonProperty("propertyName")
    public String getProperty() {
        return propertyName.orElse(null);
    }

    @JsonProperty("propertyName")
    public String getProperty() {
        return propertyName.orElse(null);
    }

    public void setPropertyName(Optional<String> propertyName) {
        this.propertyName = propertyName;
    }

    public void setProperty(String propertyName) {
        this.propertyName = Optional.ofNullable(propertyName);
    }

    public static ValidationMessage withMessageAndKey(String message, String key){
        ValidationMessage aptVM = new ValidationMessage();
        aptVM.setMessage(message);
        aptVM.setKey(key);
        aptVM.setPropertyName(Optional.of(""));
        aptVM.setId(Optional.of(0l));
        return aptVM;
    }

    public ValidationMessage(String key,String message){
        this.message =message;
        this.key =key;
        this.setPropertyName(Optional.of(""));
        this.setId(Optional.of(0l));

    }

    public static void main(String[] argv) throws Exception
    {
        String content = "{\"propertyName\":\"goalTypeId\",\"objectName\":\"order\",\"id\":21,\"message\":\"Not a valid value for an enumerated field\",\"key\":\"property.enum\"}";

        ObjectMapper mapper = new ObjectMapper();
        ValidationMessage msg = mapper.readValue(content, ValidationMessage.class);
        System.out.println(msg.toString());
    }
}
```

**Comment by cowtowncoder** [comment]
`Optional` is only supported when using `jackson-datatype-jdk8` (it is not one of datatypes in JDK7, which is baseline for Jackson 2.8), so I wouldn't expect it to work without registering that. Would this fail if JDK8 module was registered?

As to working with 2.6: I am guessing that is more accidental than as design. Due to multiple renamings and overlaps (`setPropertyName` implies `propertyName`, but there is also `setProperty`, which gets renamed via `getProperty()` having annotations), it is not immediately clear which setter would or should be used.

**Comment by xumingbo** [comment]
@cowtowncoder It works now with JDK8 module registered. It is a mystery that version 2.6.x works without JDK8 registered. 
Thank you so much.

**Comment by cowtowncoder** [comment]
@xumingbo Thank you for the update! I think there was some luck involved with 2.6.x working, regarding the order of things: I am guessing that setter with `String` was invoked, instead of one of with `Optional`.

**Comment by xumingbo** [comment]
@cowtowncoder 
Quick question: Can the method ObjectMapper.registerModule(Module module) be called multiple times with different modules?

Any advice will be greatly appreciated.

Bo Xu

**Comment by cowtowncoder** [comment]
@xumingbo Yes, expectation is that multiple modules are often registered and can co-exist.

**Comment by xumingbo** [comment]
Thank you so much, Talu!
Another quick question:  I have the impression that ObjectMapper is thread-safe, but where is the official document stating this. I need this to be put in my report.
Regards,
Bo Xu

**Comment by cowtowncoder** [comment]
@xumingbo It is thread-safe. F.ex: 

http://stackoverflow.com/questions/3907929/should-i-declare-jacksons-objectmapper-as-a-static-field

although real link is to FasterXML wiki which is currently down.

`ObjectMapper` javadocs should state this as well.

**Comment by xumingbo** [comment]
Talu,   Thank you so much.
Bo Xu
