### ISSUE TITLE
Support of JavaFX collections

### ISSUE THREAD

**Issue by agonist** [FasterXML/jackson-datatype-jdk8#5]
Hi, refering to this issue https://github.com/FasterXML/jackson-databind/issues/718 I'd like to suggest to add support for JavaFX collections since it included in JDK8.

http://docs.oracle.com/javase/8/javafx/api/javafx/beans/property/ListProperty.html
http://docs.oracle.com/javase/8/javafx/api/javafx/collections/ObservableList.html
http://docs.oracle.com/javase/8/javafx/api/javafx/beans/property/MapProperty.html
etc...

I'll try to do some PR if I do some implementaions but I don't promess

**Comment by stevenschlansker** [comment]
Seems like a reasonable addition, a PR would be very welcome :)

**Comment by cowtowncoder** [comment]
Moved to: https://github.com/FasterXML/jackson-modules-java8/issues/1
