### ISSUE TITLE
Optional with custom types

### ISSUE THREAD

**Issue by fakeh** [FasterXML/jackson-datatype-jdk8#7]
Hi,
I've come at this from a more complicated scenario, but how can I serialise and deserialise optionals whose values are complex types?

For example, the code below fails because the deserialisation creates a Double instead of an Instant (I'm using the jar310 module too):
```
		Optional<Instant> optional = mapper.readValue(mapper.writeValueAsString(Optional.of(Instant.now())), Optional.class);
		System.out.println(optional); //optional does not contain an Instant but a Double.
```

I'm hoping the answer to this will help me solve my more complex case.

Many thanks!
Dan.

**Comment by cowtowncoder** [comment]
Please use mailing lists for usage questions in future.

The problem here is Java Type Erasure; `Optional.class` does not have type parameters.
One way to handle this is to use

```
Optional<Instant> optional = mapper.readValue(source, new TypeReference<Optional<Instant>>() { });
```

but I am not sure don't you just take `Optional` part out altogether, and instead use:

```
Optional<Instant> opt = Optional.ofNullable(mapper.readValue(src, Instant.class));
```
